name: admin_web
description: "Painel administrativo da rede Nova Aliança (Flutter Web)."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  nova_alianca_core:
    path: ../packages/nova_alianca_core

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  cloud_functions: ^5.1.3

  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  intl: ^0.20.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
